typography_spectrum: 0.1471635401248932
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09160995972342789
  lightness: 0.8206311599351466
  saturation: 0.1723302686586976
  rhythmicContrast: 0.9865811096969992
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41017759311944246
analytics:
  google: null
  facebook: null
  twitter: null
name: pruebas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: tagline
purpose: []
